name: Chat-app CI/CD

on:
    pull_request:
        branches:
            - main
        paths:
            - "backend/**"
            - "frontend/**"
            - "infra/**"
            - ".github/workflows/terraform.yaml"

jobs:
    # ------------------------------------------------------------#
    # Test when submitting a pull request
    # ------------------------------------------------------------#
    terraform-plan:
        # プルリクエスト時、 test と plan 実行
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: infra/terraform

        permissions:
            id-token: write
            contents: read

        steps:
            - uses: actions/checkout@v5

            - name: Debug repository name
              run: echo "${{ github.repository }}"

            - name: Check Ubuntu version
              run: cat /etc/os-release

            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install backend dependencies
              working-directory: backend
              run: npm install

            - uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: 1.8.5

            - uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                  aws-region: ap-northeast-1

            - run: terraform init
            - run: terraform fmt -check -recursive
            - run: terraform validate
            - run: terraform test
            - run: terraform plan
